# Generated by Django 2.1.1 on 2018-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0004_auto_20181003_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='CourseProject.Article'),
        ),
    ]
