# Generated by Django 2.1.1 on 2018-10-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0005_tag_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
    ]
