# Generated by Django 2.1.1 on 2018-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0007_auto_20181005_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='CourseProject.TagForArticle', verbose_name='tags'),
        ),
    ]
