# Generated by Django 2.1.1 on 2018-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0011_auto_20181005_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='CourseProject.Tag'),
        ),
    ]
