# Generated by Django 2.1.1 on 2018-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0013_auto_20181005_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(to='CourseProject.Article'),
        ),
    ]
