# Generated by Django 2.1.1 on 2018-10-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0014_auto_20181005_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creationDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='mainText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='specialityNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
