# Generated by Django 2.1.1 on 2018-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseProject', '0015_auto_20181007_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='mainText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='specialityNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
